
list(APPEND CGTK_COMPILE_DEFINITIONS HANDY_USE_UNSTABLE_API)

find_library(LIBHANDY_LIB_ZERO handy-0.0)
find_library(LIBHANDY_LIB_ONE handy-1)

if (NOT LIBHANDY_LIB_ONE)
	if(NOT LIBHANDY_LIB_ZERO)
		message(FATAL_ERROR "Important library was not found: handy")
	else()
		set(LIBHANDY_LIB ${LIBHANDY_LIB_ZERO})
		
		list(APPEND CGTK_COMPILE_DEFINITIONS HANDY_USE_ZERO_API)
	endif()
else()
	set(LIBHANDY_LIB ${LIBHANDY_LIB_ONE})
endif()

list(APPEND CGTK_LIBRARIES ${LIBHANDY_LIB})
